package br.com.anteros.iot.things.test;

public enum LEDDisplayType {

	SIMPLE_COLOR,
	HSB_ANIMATED,
	HSL_ANIMATED,
	RAINBOW_COLOURS,
	COLOUR_WIPE_ANIMATED,
	THEATER_CHASE_ANIMATED,
	RAINBOW_ANIMATED,
	RAINBOW_CYCLE_ANIMATED,
	THEATER_CHASE_RAINBOW_ANIMATED
}
